# site name
prefixName: 
siteName: 5 A.M. Studio
# favicon and site master avatar
favicon: /images/favicon.png
avatar: https://avatars2.githubusercontent.com/u/54062596?s=200&v=4
url: http://5am.website
description: 欢迎来到5 A.M. Studio的官网哦~
cdn: 
pjax: 1
# 1开启
mathjax: 0

notice: 5 A.M. Studio Wiki已经上线啦，在导航栏的关于选项卡中可以找到！
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake }
  # 归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
  #   技术: {path: /categories/技术/, fa: fa-code }, 
  #   生活: {path: /categories/生活/, fa: fa-file-text-o }, 
  #   资源: {path: /categories/资源/, fa: fa-cloud-download }, 
  #   随想: {path: /categories/随想/, fa: fa-commenting-o },
  #   转载: {path: /categories/转载/, fa: fa-book }
  # } }
  活动: { path: javascript:;, fa: fa fa-star faa-vertical, submenus: { 
     直播: {path: https://live.bilibili.com/1781204, fa: fa fa-video-camera faa-bounce }, 
  #   番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
  #   歌单: {path: /music/, fa: fa-headphones },
  #   图集: {path: /tags/图集/, fa: fa-photo }
   } }
  
  # 友人帐: { path: /links/, fa: fa-link faa-shake }
  
  # 关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
  #   我？: {path: /about/, fa: fa-meetup}, 
  #   主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
  #   Lab: {path: /lab/, fa: fa-cogs },
  # } }
  # 广播站: { path: /Songs-FAQ, fa: fa-rss faa-pulse , submenus: {
  #   点歌: {path: https://www.wenjuan.com/s/NRneA3/ , fa: fa fa-music },
  #   歌单: {path: /Songs , fa: fa fa-list},
  #   说明: {path: /Songs-FAQ , fa: fa fa-question}
  # } }
  电视台: { path: mailto:ZYTV@5amstd.club, fa: fa-tv faa-tada }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友链: { path: javascript:;, fa: fa fa-link, submenus: {
      GamerNoTitle: { path: http://bili33.top, fa: fa fa-link},
      yuleng: { path: http://yuleng.top, fa: fa fa-link},
      TheBaiRuo: { path:http://bairuo.top, fa: fa fa-link}
  }  }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /about/ , fa: fa-leaf faa-wrench , submenus: {
    我们: { path: https://mp.weixin.qq.com/s/pYRPY5z04KSgm_aG8hL9Qw, fa: fa fa-anchor faa-tada }
    Wiki: { path: http://wiki-5am.herokuapp.com, fa: fa fa-wikipedia-w faa-tada}
  }}

  # 客户端: { path: /client/, fa: fa-android faa-vertical }



# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - http://5amfile.yuleng.top/Top-img/bg1.jpg
  - http://5amfile.yuleng.top/Top-img/bg2.jpg
  - http://5amfile.yuleng.top/Top-img/bg3.jpg
  #- http://5amfile.yuleng.top/Top-img/bg4.jpg
  - http://5amfile.yuleng.top/Top-img/bg5.jpg
  #- http://5amfile.yuleng.top/Top-img/bg6.jpg
  #- http://5amfile.yuleng.top/Top-img/bg7.jpg
  #- https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/cover/(8).jpg.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: https://mp.weixin.qq.com/s/pYRPY5z04KSgm_aG8hL9Qw, title: 嘿，我们是5 A.M. 工作室, desc: 了解我们更多哦❤~, img: http://5amfile.yuleng.top/Top-img/bg5.jpg}
  - {url: http://space.bilibili.com/388224428, title: 我们的bilibili~, desc: 最新的视频就在这里！, img: http://5amfile.yuleng.top/startdash/bilibili-16.9.jpg}
  - {url: https://cdn.bili33.workers.dev/GamerNoTitle/Picture-repo/master/Friends/5AM-Wechat.jpeg, title: 关注我们的微信公众号, desc: 欢迎关注5 A.M. Studio的微信公众号, img: https://www.pioneerbeyond.com/wp-content/uploads/2018/09/The-Ultimate-Guide-to-WeChat-teach-english-in-china.jpg}



# your site build time or founded date
siteBuildingTime: 08/13/2019 #MM/DD/YYYY

#social  url, img PC端配置
social:
  github: {url: https://github.com/5amstd, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/github.png}
  #sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  #wangyiyun: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/wangyiyun.png}
  #zhihu: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/zhihu.png}
  email: {url: mailto:server@5amstd.club, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/email.svg}
  wechat: {url: /#, qrcode: https://raw.githubusercontent.com/GamerNoTitle/Picture-repo/master/Friends/5AM-Wechat.jpeg, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wechat.png}
  bilibili: {url: http://space.bilibili.com/388224428, img: http://5amfile.yuleng.top/icon/bilibili-alpha.png}

#social  url, img 移动端配置
msocial:
  #github: {url: https://github.com/5amstd, fa: fa-github, color: 333}
  #weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  #qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}
  #email: {url: mailto:server@5amstd.club, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/email.svg}
  #wechat: {url: /#, qrcode: https://raw.githubusercontent.com/GamerNoTitle/Picture-repo/master/Friends/5AM-Wechat.jpeg, img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wechat.png}
  #bilibili: {url: http://space.bilibili.com/388224428, img: http://5amfile.yuleng.top/icon/bilibili-alpha.png}

donate:
  paypal: https://www.paypal.me/GamerNoTitle
  alipay: https://raw.githubusercontent.com/GamerNoTitle/Picture-repo/master/Donate/AliPay.jpg
  wechat: https://raw.githubusercontent.com/GamerNoTitle/Picture-repo/master/Donate/WeChatPay.png
  wechatSQ: https://raw.githubusercontent.com/GamerNoTitle/Picture-repo/master/Donate/WeChatPay.png

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: 
    - D:\OneDrive - 87ouo,Inc\Video\5 A.M. Studio\我和我的祖国 玉岩版MV.mp4
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  # name: 

aplayer: 
  id: 2292691328
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: 0yT7XHg6F8uBOjuXEIvxS92a-MdYXbMMI
v_appKey: ubKqJD6pDw8tPhXunO7qR7wm

